name: example

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    name: Example job
    steps:
      - name: Checkout
        id: start-setup
        uses: actions/checkout@v2

      - name: os-setup
        uses: vely-digital/discord-action-steps@v1
        id: os-setup
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

      - name: docker-setup
        id: docker-setup
        run: echo 'docker-setup'
        
      - name: swarm-update
        id: swarm-update
        run: echo 'swarm-update'

      - name: exit-example
        uses: vely-digital/discord-action-steps@v1
        id: exit-example
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
